services:
  stock-tracker-locust:
    image: locustio/locust:2.32.6
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
      - ./output:/mnt/output
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: root
    environment:
      - TEST_TYPE=${TEST_TYPE:-load}
      - LOCUST_LOCUSTFILE=/mnt/locust/locustfile.py
      - LOCUST_HOST=http://host.docker.internal:8080
      - LOCUST_USERS=50
      - LOCUST_SPAWN_RATE=5
